### ISSUE TITLE
Guide modal last step

### ISSUE THREAD

**Issue by neruthes** [project-maskbook/Maskbook#2]
Update according to this.

<img width="1440" alt="Screen Shot 2019-04-02 at 08 07 06" src="https://user-images.githubusercontent.com/2139261/55386335-d0aeb080-551e-11e9-8728-cb8c48b51766.png">

And I prefer to let the gray box behaving like https://encodeuri.com/ output box. Readonly; focus to select all.

<img width="1440" alt="Screen Shot 2019-04-02 at 08 09 12" src="https://user-images.githubusercontent.com/2139261/55386336-d0aeb080-551e-11e9-81e6-00ca88177da5.png">

**Comment by yisiliu** [comment]
This is better than the current one with fewer ambiguities. 
We should also guide the user to copy-paste the pubkey in the **bio** since most users never use it before.

**Comment by neruthes** [comment]
Minor adjustment.

<img width="1440" alt="Screen Shot 2019-04-02 at 10 58 32" src="https://user-images.githubusercontent.com/2139261/55397723-5c800700-5536-11e9-8669-4ccf70b047dd.png">

**Comment by Tedko** [comment]
For the restore key:

Shouldn’t we support the drop file in the gray box?

**Comment by yisiliu** [comment]
@Jack-Works ^

**Comment by neruthes** [comment]
> For the restore key:
> 
> Shouldn’t we support the drop file in the gray box?

You mean this one? It's in the Dashboard.

<img width="1002" alt="Screen Shot 2019-04-03 at 08 13 14" src="https://user-images.githubusercontent.com/2139261/55463345-5ba7ad80-55e8-11e9-99c8-b6204342cfc7.png">
