### ISSUE TITLE
Payload format

### ISSUE THREAD

**Issue by neruthes** [project-maskbook/Maskbook#4]
Let there be a space character between `with Maskbook.io:` and `🎼`.

<img width="343" alt="Screen Shot 2019-04-02 at 11 15 17" src="https://user-images.githubusercontent.com/2139261/55398658-9ce08480-5538-11e9-9766-7140bfdda0a7.png">

**Comment by Jack-Works** [comment]
No, you should say this before the release. Support two type of payload will introduce unnecessary complexity. For only a space? Not good.

**Comment by Jack-Works** [comment]
If we do this, the user with an older version has to update their extension to view the post created by newer extension. Are you sure?

**Comment by neruthes** [comment]
I am sure.

But I have a question. Why any character before 🎼 is within the matching pattern? It might not comply with common standards of i18n feasibility.
